# Generated by Django 4.2.28 on 2026-02-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_usercustomer_role_customer_userrole_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
