# Generated by Django 4.2.28 on 2026-02-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_customer_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
