def get_integration_catalog():
    return {
        "categories": [
            {"key": "all", "label": "All apps"},
            {"key": "featured", "label": "Featured"},
            {"key": "built_in", "label": "Built-in tools"},
            {"key": "productivity", "label": "Productivity"},
            {"key": "ai", "label": "AI"},
        ],
        "apps": [
            {
                "key": "jira",
                "name": "Jira Cloud Platform",
                "verified": True,
                "categories": ["all", "featured", "productivity"],
                "modules": [
                    {
                        "type": "jira.watch.issues",
                        "title": "Watch Issues",
                        "kind": "trigger",
                        "description": "Poll Jira issues every 15 minutes.",
                        "acceptsInput": False,
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.users.list",
                        "title": "List Users",
                        "kind": "action",
                        "description": "Retrieves all users (active and inactive).",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.users.search",
                        "title": "Search Users",
                        "kind": "search",
                        "description": "Search users by query.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.get",
                        "title": "Get an Issue",
                        "kind": "action",
                        "description": "Returns details for one issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.search",
                        "title": "Search Issues",
                        "kind": "search",
                        "description": "Search Jira issues using JQL.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.create",
                        "title": "Create an Issue",
                        "kind": "action",
                        "description": "Creates a new issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.update",
                        "title": "Update an Issue",
                        "kind": "action",
                        "description": "Updates an existing issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.delete",
                        "title": "Delete an Issue",
                        "kind": "action",
                        "description": "Deletes an issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.transitions.list",
                        "title": "List Transitions",
                        "kind": "search",
                        "description": "List available workflow transitions.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.status.update",
                        "title": "Update Status",
                        "kind": "action",
                        "description": "Move issue to a transition status.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.assign",
                        "title": "Assign Issue",
                        "kind": "action",
                        "description": "Assign issue to a user.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.unassign",
                        "title": "Unassign Issue",
                        "kind": "action",
                        "description": "Remove assignee from an issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.changelog.list",
                        "title": "List Changelog",
                        "kind": "search",
                        "description": "Fetch issue changelog entries.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.comment.create",
                        "title": "Add a Comment",
                        "kind": "action",
                        "description": "Adds a comment to an issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.comment.list",
                        "title": "List Comments",
                        "kind": "search",
                        "description": "List comments for an issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.comment.get",
                        "title": "Get Comment",
                        "kind": "action",
                        "description": "Fetch a single issue comment.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.comment.update",
                        "title": "Update Comment",
                        "kind": "action",
                        "description": "Update an existing issue comment.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.comment.delete",
                        "title": "Delete Comment",
                        "kind": "action",
                        "description": "Delete a comment from an issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.link.create",
                        "title": "Create Issue Link",
                        "kind": "action",
                        "description": "Create link between issues.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.link.get",
                        "title": "Get Issue Link",
                        "kind": "action",
                        "description": "Get issue link details.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.link.delete",
                        "title": "Delete Issue Link",
                        "kind": "action",
                        "description": "Delete issue link by id.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.watcher.list",
                        "title": "List Watchers",
                        "kind": "search",
                        "description": "List issue watchers.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.watcher.add",
                        "title": "Add Watcher",
                        "kind": "action",
                        "description": "Add watcher to issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.watcher.remove",
                        "title": "Remove Watcher",
                        "kind": "action",
                        "description": "Remove watcher from issue.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.attachment.add",
                        "title": "Add Attachment",
                        "kind": "action",
                        "description": "Attach file to issue (base64 payload).",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.attachment.get",
                        "title": "Get Attachment",
                        "kind": "action",
                        "description": "Get attachment metadata.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.attachment.content",
                        "title": "Get Attachment Content",
                        "kind": "action",
                        "description": "Download attachment content endpoint response.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.issue.attachment.delete",
                        "title": "Delete Attachment",
                        "kind": "action",
                        "description": "Delete attachment by id.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.field.list",
                        "title": "List Fields",
                        "kind": "search",
                        "description": "List available fields.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.field.create",
                        "title": "Create Field",
                        "kind": "action",
                        "description": "Create custom field.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.field.update",
                        "title": "Update Field",
                        "kind": "action",
                        "description": "Update custom field.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.field.delete",
                        "title": "Delete Field",
                        "kind": "action",
                        "description": "Delete custom field.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.field.option.list",
                        "title": "List Field Options",
                        "kind": "search",
                        "description": "List options for field context.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.field.option.create",
                        "title": "Create Field Options",
                        "kind": "action",
                        "description": "Create options for field context.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.field.option.update",
                        "title": "Update Field Options",
                        "kind": "action",
                        "description": "Update options in field context.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.field.option.delete",
                        "title": "Delete Field Option",
                        "kind": "action",
                        "description": "Delete a field option by id.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.field.option.reorder",
                        "title": "Reorder Field Options",
                        "kind": "action",
                        "description": "Reorder field options in context.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.component.list",
                        "title": "List Project Components",
                        "kind": "search",
                        "description": "List components for a project.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.component.create",
                        "title": "Create Project Component",
                        "kind": "action",
                        "description": "Create project component.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.component.get",
                        "title": "Get Project Component",
                        "kind": "action",
                        "description": "Get project component by id.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.component.update",
                        "title": "Update Project Component",
                        "kind": "action",
                        "description": "Update project component by id.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.component.delete",
                        "title": "Delete Project Component",
                        "kind": "action",
                        "description": "Delete project component by id.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.version.list",
                        "title": "List Project Versions",
                        "kind": "search",
                        "description": "List versions for a project.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.version.create",
                        "title": "Create Project Version",
                        "kind": "action",
                        "description": "Create project version.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.version.get",
                        "title": "Get Project Version",
                        "kind": "action",
                        "description": "Get project version by id.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.version.update",
                        "title": "Update Project Version",
                        "kind": "action",
                        "description": "Update project version.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.project.version.delete",
                        "title": "Delete Project Version",
                        "kind": "action",
                        "description": "Delete project version.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "jira.api.call",
                        "title": "Make an API Call",
                        "kind": "utility",
                        "description": "Execute a custom Jira REST API request.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                ],
            },
            {
                "key": "jenkins",
                "name": "Jenkins",
                "verified": True,
                "categories": ["all", "featured", "built_in"],
                "modules": [
                    {
                        "type": "jenkins.api.call",
                        "title": "Make an API Call",
                        "kind": "utility",
                        "description": "Execute any Jenkins API call using OAuth bearer token.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                ],
            },
            {
                "key": "flow_control",
                "name": "Flow Control",
                "verified": False,
                "categories": ["all", "built_in"],
                "modules": [
                    {
                        "type": "flow.router",
                        "title": "Router",
                        "kind": "utility",
                        "description": "Split execution into branching paths.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    }
                ],
            },
            {
                "key": "webhooks",
                "name": "Webhooks",
                "verified": False,
                "categories": ["all", "built_in"],
                "modules": [],
            },
            {
                "key": "http",
                "name": "HTTP",
                "verified": False,
                "categories": ["all", "built_in"],
                "modules": [
                    {
                        "type": "http.make_request",
                        "title": "Make a request",
                        "kind": "action",
                        "description": "Send any HTTP request and capture response payload.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "http.download_file",
                        "title": "Download a file",
                        "kind": "action",
                        "description": "Download file bytes from URL and return base64 output.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "http.resolve_url",
                        "title": "Resolve URL",
                        "kind": "utility",
                        "description": "Follow redirects and return the final resolved URL.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                ],
            },
            {
                "key": "json",
                "name": "JSON",
                "verified": False,
                "categories": ["all", "built_in"],
                "modules": [
                    {
                        "type": "json.create",
                        "title": "Create JSON",
                        "kind": "utility",
                        "description": "Build JSON output from mapped values for downstream nodes.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    }
                ],
            },
            {
                "key": "gmail",
                "name": "Gmail",
                "verified": False,
                "categories": ["all", "productivity"],
                "modules": [],
            },
            {
                "key": "hubspot",
                "name": "HubSpot CRM",
                "verified": True,
                "categories": ["all", "featured", "productivity"],
                "modules": [
                    {
                        "type": "hubspot.crm.objects.search",
                        "title": "Search for CRM Objects",
                        "kind": "search",
                        "description": "Search contacts, companies, deals, tickets, products or custom object records.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.crm.list.members.add",
                        "title": "Add Members to a List",
                        "kind": "action",
                        "description": "Add records to a HubSpot list.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.crm.list.members.delete",
                        "title": "Delete Members from a List",
                        "kind": "action",
                        "description": "Remove records from a HubSpot list.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.crm.record.property.get",
                        "title": "Get a Record Property",
                        "kind": "action",
                        "description": "Fetch metadata for a specific CRM record property.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.custom_object.record.create",
                        "title": "Create a Custom Object Record",
                        "kind": "action",
                        "description": "Create a custom object record and return the created object.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.custom_object.record.get",
                        "title": "Get a Custom Object Record",
                        "kind": "action",
                        "description": "Fetch a custom object record by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.custom_object.record.update",
                        "title": "Update a Custom Object Record",
                        "kind": "action",
                        "description": "Update custom object record properties by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.custom_object.record.delete",
                        "title": "Delete a Custom Object Record",
                        "kind": "action",
                        "description": "Delete a custom object record by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.contact.create",
                        "title": "Create a Contact",
                        "kind": "action",
                        "description": "Create a contact.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.contact.update",
                        "title": "Update a Contact",
                        "kind": "action",
                        "description": "Update contact properties by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.contact.get",
                        "title": "Get a Contact",
                        "kind": "action",
                        "description": "Get a contact by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.contact.search",
                        "title": "Search for Contacts",
                        "kind": "search",
                        "description": "Search contacts using query, filters, and sorts.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.contact.merge",
                        "title": "Merge Contacts",
                        "kind": "action",
                        "description": "Merge two contacts into one.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.contact.delete",
                        "title": "Delete a Contact",
                        "kind": "action",
                        "description": "Delete a contact by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.deal.create",
                        "title": "Create a Deal",
                        "kind": "action",
                        "description": "Create a deal.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.deal.update",
                        "title": "Update a Deal",
                        "kind": "action",
                        "description": "Update a deal by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.deal.get",
                        "title": "Get a Deal",
                        "kind": "action",
                        "description": "Get a deal by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.deal.search",
                        "title": "Search for Deals",
                        "kind": "search",
                        "description": "Search deals with query/filter criteria.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.deal.delete",
                        "title": "Delete a Deal",
                        "kind": "action",
                        "description": "Delete a deal by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.company.create",
                        "title": "Create a Company",
                        "kind": "action",
                        "description": "Create a company.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.company.update",
                        "title": "Update a Company",
                        "kind": "action",
                        "description": "Update company properties by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.company.get",
                        "title": "Get a Company",
                        "kind": "action",
                        "description": "Get a company by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.company.search",
                        "title": "Search for Companies",
                        "kind": "search",
                        "description": "Search companies with query/filter criteria.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.company.delete",
                        "title": "Delete a Company",
                        "kind": "action",
                        "description": "Delete a company by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.engagement.create",
                        "title": "Create an Engagement",
                        "kind": "action",
                        "description": "Create an engagement record (task/note/call/etc).",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.engagement.delete",
                        "title": "Delete an Engagement",
                        "kind": "action",
                        "description": "Delete an engagement by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.timeline.event.create",
                        "title": "Create a Timeline Event",
                        "kind": "action",
                        "description": "Create or update timeline events.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.timeline.event_templates.list",
                        "title": "List Timeline Event Templates",
                        "kind": "search",
                        "description": "List available timeline event templates.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.file.folder.create",
                        "title": "Create a Folder",
                        "kind": "action",
                        "description": "Create a file manager folder.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.file.list",
                        "title": "List Files",
                        "kind": "search",
                        "description": "List files from HubSpot file manager.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.file.upload",
                        "title": "Upload a File",
                        "kind": "action",
                        "description": "Upload a file to HubSpot file manager.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.file.update",
                        "title": "Update File Properties",
                        "kind": "action",
                        "description": "Update file metadata by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.file.folder.delete",
                        "title": "Delete a Folder",
                        "kind": "action",
                        "description": "Delete a file manager folder by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.owner.get",
                        "title": "Get an Owner",
                        "kind": "action",
                        "description": "Get owner details by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.owner.list",
                        "title": "List Owners",
                        "kind": "search",
                        "description": "List account owners.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.ticket.create",
                        "title": "Create a Ticket",
                        "kind": "action",
                        "description": "Create a support ticket.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.ticket.update",
                        "title": "Update a Ticket",
                        "kind": "action",
                        "description": "Update ticket properties by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.ticket.get",
                        "title": "Get a Ticket",
                        "kind": "action",
                        "description": "Get ticket details by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.ticket.search",
                        "title": "Search for Tickets",
                        "kind": "search",
                        "description": "Search tickets with query/filter criteria.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.ticket.delete",
                        "title": "Delete a Ticket",
                        "kind": "action",
                        "description": "Delete a ticket by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.form.uploaded_file.get",
                        "title": "Get a File Uploaded via Form",
                        "kind": "action",
                        "description": "Get a file uploaded via HubSpot form by file ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.form.list",
                        "title": "List Forms",
                        "kind": "search",
                        "description": "List forms in HubSpot account.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.form.submit",
                        "title": "Submit Data to a Form",
                        "kind": "action",
                        "description": "Submit form data to a HubSpot form endpoint.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.workflow.contact.add",
                        "title": "Add a Contact to a Workflow",
                        "kind": "action",
                        "description": "Enroll a contact into a workflow.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.workflow.contact.remove",
                        "title": "Remove a Contact from a Workflow",
                        "kind": "action",
                        "description": "Remove a contact from workflow enrollment.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.subscription.contact.subscribe",
                        "title": "Subscribe Contact",
                        "kind": "action",
                        "description": "Subscribe a contact to communication preferences.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.subscription.contact.unsubscribe",
                        "title": "Unsubscribe a Contact",
                        "kind": "action",
                        "description": "Unsubscribe a contact from communication preferences.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.quote.get",
                        "title": "Get a Quote",
                        "kind": "action",
                        "description": "Get quote details by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.quote.update",
                        "title": "Update a Quote",
                        "kind": "action",
                        "description": "Update quote properties by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.quote.delete",
                        "title": "Delete a Quote",
                        "kind": "action",
                        "description": "Delete quote by ID.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                    {
                        "type": "hubspot.api.call",
                        "title": "Make an API Call",
                        "kind": "utility",
                        "description": "Execute any authorized HubSpot API request.",
                        "acceptsInput": True,
                        "inputPortType": "event",
                        "outputPortType": "event",
                    },
                ],
            },
            {
                "key": "slack",
                "name": "Slack",
                "verified": False,
                "categories": ["all", "productivity"],
                "modules": [],
            },
            {
                "key": "notion",
                "name": "Notion",
                "verified": False,
                "categories": ["all", "productivity"],
                "modules": [],
            },
        ],
    }
