# Generated by Django 4.2.27 on 2026-03-06 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0010_customer_address_line_1_customer_address_line_2_and_more"),
        ("app", "0002_run_scenario_scenarioversion_scenarioschedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("support", "Support"),
                            ("sales", "Sales"),
                            ("reminder", "Reminder"),
                            ("internal_notification", "Internal Notification"),
                        ],
                        default="transactional",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("subject_template", models.TextField(blank=True, default="")),
                ("html_template", models.TextField(blank=True, default="")),
                ("text_template", models.TextField(blank=True, default="")),
                ("variables_schema", models.JSONField(blank=True, default=list)),
                ("sample_payload", models.JSONField(blank=True, default=dict)),
                ("is_system_template", models.BooleanField(default=False)),
                ("current_version", models.PositiveIntegerField(default=1)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orchestrate_email_templates",
                        to="identity.tenant",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orchestrate_email_templates",
                        to="identity.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("support", "Support"),
                            ("sales", "Sales"),
                            ("reminder", "Reminder"),
                            ("internal_notification", "Internal Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("subject_template", models.TextField(blank=True, default="")),
                ("html_template", models.TextField(blank=True, default="")),
                ("text_template", models.TextField(blank=True, default="")),
                ("variables_schema", models.JSONField(blank=True, default=list)),
                ("sample_payload", models.JSONField(blank=True, default=dict)),
                (
                    "change_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="app.emailtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddConstraint(
            model_name="emailtemplateversion",
            constraint=models.UniqueConstraint(
                fields=("template", "version"), name="unique_email_template_version"
            ),
        ),
    ]
