# Generated by Django 4.2.29 on 2026-03-06 08:19

from django.db import migrations, models
from django.db.models import F


def backfill_queued_at_for_queued_runs(apps, schema_editor):
    Run = apps.get_model("app", "Run")
    Run.objects.filter(status="queued", queued_at__isnull=True).update(queued_at=F("created_at"))


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_seed_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='encrypted_secret_payload',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='connection',
            name='secret_payload_migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenarioschedule',
            name='last_enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_queued_at_for_queued_runs,
            noop_reverse,
        ),
    ]
