# Generated by Django 4.2.27 on 2026-03-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_connection_encrypted_secret_payload_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("event_label", models.CharField(max_length=255)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="app.run",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="app.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
